# Copyright(c) 2022, Oracle and / or its affiliates.
# All rights reserved. The Universal Permissive License(UPL), Version 1.0 as shown at http: // oss.oracle.com/licenses/upl
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-bdg-deploy
  labels:
    app: oci-bdg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oci-bdg
  template:
    metadata:
      labels:
        app: oci-bdg
    spec:
      containers:
        - name: oci-bdg
          image: iad.ocir.io/ociobenablement/oci-bdg:latest
          env:
            - name: PropsFile
              valueFrom:
                configMapKeyRef:
                  name: oci-synthetic-bridge
                  key: PropsFile
            - name: isMultiPass
              valueFrom:
                configMapKeyRef:
                  name: oci-synthetic-bridge
                  key: isMultiPass
            - name: Synthetic1__prefix
              valueFrom:
                configMapKeyRef:
                  name: oci-synthetic-bridge
                  key: Synthetic1__prefix
      imagePullSecrets:
        - name: ocirsecret-oci-bdg
