apiVersion: v1
kind: ConfigMap
metadata:
  name: oci-bridge-multi-cloud
data:
  ListConnectorProps: "True"
  milliDelayOnMultiPass: "10000"
  Synthetic1__pass_all: "true"
  Synthetic1__total_msgs: "1"
  Synthetic1__prefix: "cloud "
  PropsFile: "bridge-multi-cloud.properties"
  isMultiPass: "true"
  OCIQueue__OCI_REGION: "us-ashburn-1"
  OCIQueue__OCI_QUEUEID: "ocid1.queue.oc1.iad.aaaaaaaaaaaaaaaaaaaaaaa"
